---
# tasks file for tomcat-ansible-role

- name: Install Java
  yum:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ tomcat_java_packages_EL }}"
  when: tomcat_install_java|bool

- name: Check if tomcat is already installed
  stat:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: is_installed

- name: Create group {{ tomcat_group }}
  group:
    name: "{{ tomcat_group }}"
    gid: "{{ tomcat_group_gid | default(omit) }}"
    state: present

- name: Create user {{ tomcat_user }}
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    uid: "{{ tomcat_user_uid | default(omit) }}"
    state: present

- name: Create temp directory
  file:
    path: '{{ tomcat_temp_download_path }}'
    state: directory
  delegate_to: "{{ item }}"
  loop:
  - localhost
  - "{{ inventory_hostname }}"
  changed_when: False
  when: >
    not is_installed.stat.exists and
    (( item == inventory_hostname ) or tomcat_remote_is_disconnected )

- name: Download apache-tomcat-{{ tomcat_version }}.tar.gz
  get_url:
    url: "{{ tomcat_downloadURL }}/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: '{{ tomcat_temp_download_path }}'
    timeout: 120
  delegate_to: "{{ 'localhost' if tomcat_remote_is_disconnected else inventory_hostname }}"
  when: not is_installed.stat.exists

- name: apache-tomcat-{{ tomcat_version }}.tar.gz is transfered to the disconnected remote
  copy:
    src: "{{ tomcat_temp_download_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_temp_download_path }}"
  when: tomcat_remote_is_disconnected

- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz at {{ tomcat_install_path }}
  unarchive:
    src: "{{ tomcat_temp_download_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}"
    remote_src: True
    owner: "{% if tomcat_permissions_production %}root{% else %}{{ tomcat_user }}{% endif %}"
    group: "{{ tomcat_group }}"
    creates: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: tomcat_installed
  when: not is_installed.stat.exists

- name: Clean up temporary files
  file:
    path: '{{ tomcat_temp_download_path }}'
    state: absent
  changed_when: False
  when: not is_installed.stat.exists
